### ISSUE TITLE
[feature request] showImgsInBrowser supports animated gif

### ISSUE THREAD

**Issue by qianyizhang** [DIYer22/boxx#13]
hi,
can you please add supports for animated gif?
currently it only displays the first static frame.

also it would be nice if the number of images displayed per row can be user specific (eg. organized by folder)

thanks!

**Comment by DIYer22** [comment]
It's a  huge job to support gif in html canvas.
I heighly  recommend using MegSpot instead.
MegSpot supports GIF and could be started with cli, e.g.
```
megspot a.gif b.gif -c
```
https://github.com/MegEngine/MegSpot

**Comment by qianyizhang** [comment]
thanks for the tips.
However, in my usecase, I prefer to work with simple visualization lib/html.
So the data stays in remote server, and saves the trouble of syncing/downloading.

**Comment by DIYer22** [comment]
我给 megspot 提了个  [支持 server 模式的 feature request](https://github.com/MegEngine/MegSpot/issues/8)
