### ISSUE TITLE
Apply for some useful functionality

### ISSUE THREAD

**Issue by XiaoyuZHK** [DIYer22/boxx#15]
Hello, @DIYer22 , thanks for your contribution. I am a CV beginner and this tool is very useful.
In addition, can you add more functionality about image processing?     For example: visual feature map, show attention on the image, show annotation on the image, even statistical image features in image datasets and so on.    
Looking forward to your reply ! :)      
thanks again for everything ！:>

**Comment by DIYer22** [comment]
Thank you for your sincere advice. I am planning to refactor this tool, would you like to help rebuild this tool? 
Have a nice day :smile:

**Comment by XiaoyuZHK** [comment]
I hope I can, in the near future. 🥰
