### ISSUE TITLE
About `with p:`

### ISSUE THREAD

**Issue by zodiac911** [DIYer22/boxx#2]
非常好的调试工具，被爱可可大大在微博推荐了，估计会涨一波 start 吧

运行 tutorial 的时候发现一个问题，不知道是不是我对 Python 的理解太差了

![image](https://user-images.githubusercontent.com/19172379/41754541-559d4850-7605-11e8-98db-03cd14af740e.png)
![image](https://user-images.githubusercontent.com/19172379/41754556-6342da9c-7605-11e8-8ee5-a99d7efad2df.png)

是关于 with p 的上下文管理，似乎因为 前面 import boxx.p 之后出现了命名空间的污染？

**Comment by zodiac911** [comment]
Python 3.6 Windows 环境

**Comment by DIYer22** [comment]
@zodiac911 对，这的确是BUG  `import boxx.{操作}` 这个方式非常 trick 而且 Python2 和 Python3 结构上的不同导致 实现方式不同，效果也不同

在 Python 2 里面过 `import boxx.{操作}` 再 `from boxx import {操作}`是没有问题的， 但是  `import boxx.{操作}` 只能运行第一次

在 Python 3 里面  `import boxx.{操作}` 每次都能运行，但是再执行 `from boxx import {操作}`就被污染了

所以 tutorial 里面推荐 在不打算导入 `import boxx` 时才用 `import boxx.{操作}`

或者先执行 `from boxx import {操作}` 再执行  `import boxx.{操作}` 也 OK

**Comment by zodiac911** [comment]
@DIYer22 Thanks a lot, 
I will stay with ‘from boxx import p: p()'
