### ISSUE TITLE
Import hangs in jupyter notebook

### ISSUE THREAD

**Issue by Larry-u** [DIYer22/boxx#5]
I use jupyter notebook in the conda virtual environment. What is weird is that I **randomly** encountered this problem, which means sometimes directly using `from boxx import show` is ok but sometimes it hangs. 

In the virtual environment, when I import boxx in python CLE, it runs normally. However, in jupyter notebook, it hangs a long time.

I tried install it within the jupyter kernel using `!python -m pip install boxx`, but it says it's already satisfied.
Also, I compared the `sys.path` in python CLE and which in jupyter, results are the same...

Could anyone helps? Thanks in advance.

**Comment by DIYer22** [comment]
when  it hangs, try `interrupt the kernel`, then see the Error Message. 
Error Message will show you where the programs hangs.

![image](https://user-images.githubusercontent.com/10448025/45080441-7df74c80-b127-11e8-919f-cef35eb7e186.png)

and paste the Error Message here.

**Comment by Larry-u** [comment]
Thank you for your immediately reply.
I followed your instruction and weird thing happened.

When I click interrupt the kernel, jupyter prompting "interrupting the kernel", and no error message shows. The kernel is still hangs until I twice click the interrupt button.

Then I run the import line again, it succeeds...
Hard to debug...

**Comment by Larry-u** [comment]
After another try... I found an empirical solution :joy:
That is when jupyter hangs, click the interrupt button twice...
Then it imported successfully. lol
And I think this is why I randomly encountered this problem :joy:

**Comment by DIYer22** [comment]
So Hard to debug😂...
