### ISSUE TITLE
[Question]  how to use showImgsInBrowser on remote server?

### ISSUE THREAD

**Issue by qianyizhang** [DIYer22/boxx#8]
can it run like SimpleHTTPServer?

**Comment by DIYer22** [comment]
Thank you for your suggestion.    
I have update the `showImgsInBrowser` code just now, to support remote server.   
You can follow those steps to try "showImgsInBrowser on remote server":
1. update your `boxx` to latest (`__version__` >= 0.9.2.12)
1. run code `shows([img] * 4)`
1. run `python -m SimpleHTTPServer` at `/tmp` dir
1. open `http://{remote_ip_address}:8000/shows/` in web browser

**Comment by qianyizhang** [comment]
nice
